apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/eshoplite-default: "true"
        io.kompose.service: backend
    spec:
      containers:
        - image: eshopcontainerregistry234.azurecr.io/productservice:v1
          name: backend
          ports:
            - containerPort: 8080
              hostPort: 5200
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
