version: '3.4'

services: 

  frontend:
    image: storeimage
    build:
      context: .
      dockerfile: DockerfileStore
    environment: 
      - ProductEndpoint=http://backend:8080
      - ImagePrefix=https://glowing-sniffle-vgggvpg9vpjhpj66-5200.app.github.dev/images
    ports:
      - "5902:8080"
    depends_on: 
      - backend
  backend:
    image: productservice
    build: 
      context: .
      dockerfile: DockerfileProducts
    ports: 
      - "5200:8080"