apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.30.0 (9d8dcb518)
      creationTimestamp: null
      labels:
        io.kompose.network/eshoplite-default: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: ImagePrefix
              value: http://backend:8080/images
            - name: ProductEndpoint
              value: http://backend:8080
          image: eshopcontainerregistry234.azurecr.io/storeimage:v1
          name: frontend
          ports:
            - containerPort: 8080
              hostPort: 5902
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
